master:
  image: fokkodriesprong/docker-spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_MASTER_IP: master
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master:/conf
    - /tmp/spark-events:/tmp/spark-events

worker:
  image: fokkodriesprong/docker-spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
  links:
    - master
  volumes:
    - ./conf/worker:/conf
    - /tmp/spark-events:/tmp/spark-events

history:
  image: fokkodriesprong/docker-spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer
  hostname: history
  links:
    - master
  volumes:
    - ./conf/history:/conf
    - /tmp/spark-events:/tmp/spark-events
